package model;

public class Line {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_id
     *
     * @mbg.generated
     */
    private String lineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.line_name
     *
     * @mbg.generated
     */
    private String lineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.begin_province_number
     *
     * @mbg.generated
     */
    private String beginProvinceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.begin_city_number
     *
     * @mbg.generated
     */
    private String beginCityNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.midpoint_province_number
     *
     * @mbg.generated
     */
    private String midpointProvinceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.midpoint_city_number
     *
     * @mbg.generated
     */
    private String midpointCityNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.destination_province_number
     *
     * @mbg.generated
     */
    private String destinationProvinceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.destination_city_number
     *
     * @mbg.generated
     */
    private String destinationCityNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.ransport_price
     *
     * @mbg.generated
     */
    private Long ransportPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_id
     *
     * @return the value of line.line_id
     *
     * @mbg.generated
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_id
     *
     * @param lineId the value for line.line_id
     *
     * @mbg.generated
     */
    public void setLineId(String lineId) {
        this.lineId = lineId == null ? null : lineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.line_name
     *
     * @return the value of line.line_name
     *
     * @mbg.generated
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.line_name
     *
     * @param lineName the value for line.line_name
     *
     * @mbg.generated
     */
    public void setLineName(String lineName) {
        this.lineName = lineName == null ? null : lineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.begin_province_number
     *
     * @return the value of line.begin_province_number
     *
     * @mbg.generated
     */
    public String getBeginProvinceNumber() {
        return beginProvinceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.begin_province_number
     *
     * @param beginProvinceNumber the value for line.begin_province_number
     *
     * @mbg.generated
     */
    public void setBeginProvinceNumber(String beginProvinceNumber) {
        this.beginProvinceNumber = beginProvinceNumber == null ? null : beginProvinceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.begin_city_number
     *
     * @return the value of line.begin_city_number
     *
     * @mbg.generated
     */
    public String getBeginCityNumber() {
        return beginCityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.begin_city_number
     *
     * @param beginCityNumber the value for line.begin_city_number
     *
     * @mbg.generated
     */
    public void setBeginCityNumber(String beginCityNumber) {
        this.beginCityNumber = beginCityNumber == null ? null : beginCityNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.midpoint_province_number
     *
     * @return the value of line.midpoint_province_number
     *
     * @mbg.generated
     */
    public String getMidpointProvinceNumber() {
        return midpointProvinceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.midpoint_province_number
     *
     * @param midpointProvinceNumber the value for line.midpoint_province_number
     *
     * @mbg.generated
     */
    public void setMidpointProvinceNumber(String midpointProvinceNumber) {
        this.midpointProvinceNumber = midpointProvinceNumber == null ? null : midpointProvinceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.midpoint_city_number
     *
     * @return the value of line.midpoint_city_number
     *
     * @mbg.generated
     */
    public String getMidpointCityNumber() {
        return midpointCityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.midpoint_city_number
     *
     * @param midpointCityNumber the value for line.midpoint_city_number
     *
     * @mbg.generated
     */
    public void setMidpointCityNumber(String midpointCityNumber) {
        this.midpointCityNumber = midpointCityNumber == null ? null : midpointCityNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.destination_province_number
     *
     * @return the value of line.destination_province_number
     *
     * @mbg.generated
     */
    public String getDestinationProvinceNumber() {
        return destinationProvinceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.destination_province_number
     *
     * @param destinationProvinceNumber the value for line.destination_province_number
     *
     * @mbg.generated
     */
    public void setDestinationProvinceNumber(String destinationProvinceNumber) {
        this.destinationProvinceNumber = destinationProvinceNumber == null ? null : destinationProvinceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.destination_city_number
     *
     * @return the value of line.destination_city_number
     *
     * @mbg.generated
     */
    public String getDestinationCityNumber() {
        return destinationCityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.destination_city_number
     *
     * @param destinationCityNumber the value for line.destination_city_number
     *
     * @mbg.generated
     */
    public void setDestinationCityNumber(String destinationCityNumber) {
        this.destinationCityNumber = destinationCityNumber == null ? null : destinationCityNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.ransport_price
     *
     * @return the value of line.ransport_price
     *
     * @mbg.generated
     */
    public Long getRansportPrice() {
        return ransportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.ransport_price
     *
     * @param ransportPrice the value for line.ransport_price
     *
     * @mbg.generated
     */
    public void setRansportPrice(Long ransportPrice) {
        this.ransportPrice = ransportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.notes
     *
     * @return the value of line.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.notes
     *
     * @param notes the value for line.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}