package model;

public class OrderForm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_type
     *
     * @mbg.generated
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_number
     *
     * @mbg.generated
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.commodity_name
     *
     * @mbg.generated
     */
    private String commodityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.cargo_weight
     *
     * @mbg.generated
     */
    private Integer cargoWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.mail_people
     *
     * @mbg.generated
     */
    private String mailPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.mail_address
     *
     * @mbg.generated
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.place_receipt
     *
     * @mbg.generated
     */
    private String placeReceipt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.order_state
     *
     * @mbg.generated
     */
    private Integer orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.mail_people_phone
     *
     * @mbg.generated
     */
    private String mailPeoplePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.consignee_number
     *
     * @mbg.generated
     */
    private String consigneeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.origin_city
     *
     * @mbg.generated
     */
    private String originCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.midpoint_city
     *
     * @mbg.generated
     */
    private String midpointCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.destination_city
     *
     * @mbg.generated
     */
    private String destinationCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.ship_price
     *
     * @mbg.generated
     */
    private Long shipPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.dispatching_price
     *
     * @mbg.generated
     */
    private Long dispatchingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.transport_price
     *
     * @mbg.generated
     */
    private Long transportPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.total_price
     *
     * @mbg.generated
     */
    private String totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.vehicle
     *
     * @mbg.generated
     */
    private String vehicle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_form.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_id
     *
     * @return the value of order_form.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_id
     *
     * @param orderId the value for order_form.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_type
     *
     * @return the value of order_form.order_type
     *
     * @mbg.generated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_type
     *
     * @param orderType the value for order_form.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_number
     *
     * @return the value of order_form.order_number
     *
     * @mbg.generated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_number
     *
     * @param orderNumber the value for order_form.order_number
     *
     * @mbg.generated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.commodity_name
     *
     * @return the value of order_form.commodity_name
     *
     * @mbg.generated
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.commodity_name
     *
     * @param commodityName the value for order_form.commodity_name
     *
     * @mbg.generated
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.cargo_weight
     *
     * @return the value of order_form.cargo_weight
     *
     * @mbg.generated
     */
    public Integer getCargoWeight() {
        return cargoWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.cargo_weight
     *
     * @param cargoWeight the value for order_form.cargo_weight
     *
     * @mbg.generated
     */
    public void setCargoWeight(Integer cargoWeight) {
        this.cargoWeight = cargoWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.mail_people
     *
     * @return the value of order_form.mail_people
     *
     * @mbg.generated
     */
    public String getMailPeople() {
        return mailPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.mail_people
     *
     * @param mailPeople the value for order_form.mail_people
     *
     * @mbg.generated
     */
    public void setMailPeople(String mailPeople) {
        this.mailPeople = mailPeople == null ? null : mailPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.mail_address
     *
     * @return the value of order_form.mail_address
     *
     * @mbg.generated
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.mail_address
     *
     * @param mailAddress the value for order_form.mail_address
     *
     * @mbg.generated
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress == null ? null : mailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.place_receipt
     *
     * @return the value of order_form.place_receipt
     *
     * @mbg.generated
     */
    public String getPlaceReceipt() {
        return placeReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.place_receipt
     *
     * @param placeReceipt the value for order_form.place_receipt
     *
     * @mbg.generated
     */
    public void setPlaceReceipt(String placeReceipt) {
        this.placeReceipt = placeReceipt == null ? null : placeReceipt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.order_state
     *
     * @return the value of order_form.order_state
     *
     * @mbg.generated
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.order_state
     *
     * @param orderState the value for order_form.order_state
     *
     * @mbg.generated
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.mail_people_phone
     *
     * @return the value of order_form.mail_people_phone
     *
     * @mbg.generated
     */
    public String getMailPeoplePhone() {
        return mailPeoplePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.mail_people_phone
     *
     * @param mailPeoplePhone the value for order_form.mail_people_phone
     *
     * @mbg.generated
     */
    public void setMailPeoplePhone(String mailPeoplePhone) {
        this.mailPeoplePhone = mailPeoplePhone == null ? null : mailPeoplePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.consignee
     *
     * @return the value of order_form.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.consignee
     *
     * @param consignee the value for order_form.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.consignee_number
     *
     * @return the value of order_form.consignee_number
     *
     * @mbg.generated
     */
    public String getConsigneeNumber() {
        return consigneeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.consignee_number
     *
     * @param consigneeNumber the value for order_form.consignee_number
     *
     * @mbg.generated
     */
    public void setConsigneeNumber(String consigneeNumber) {
        this.consigneeNumber = consigneeNumber == null ? null : consigneeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.origin_city
     *
     * @return the value of order_form.origin_city
     *
     * @mbg.generated
     */
    public String getOriginCity() {
        return originCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.origin_city
     *
     * @param originCity the value for order_form.origin_city
     *
     * @mbg.generated
     */
    public void setOriginCity(String originCity) {
        this.originCity = originCity == null ? null : originCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.midpoint_city
     *
     * @return the value of order_form.midpoint_city
     *
     * @mbg.generated
     */
    public String getMidpointCity() {
        return midpointCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.midpoint_city
     *
     * @param midpointCity the value for order_form.midpoint_city
     *
     * @mbg.generated
     */
    public void setMidpointCity(String midpointCity) {
        this.midpointCity = midpointCity == null ? null : midpointCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.destination_city
     *
     * @return the value of order_form.destination_city
     *
     * @mbg.generated
     */
    public String getDestinationCity() {
        return destinationCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.destination_city
     *
     * @param destinationCity the value for order_form.destination_city
     *
     * @mbg.generated
     */
    public void setDestinationCity(String destinationCity) {
        this.destinationCity = destinationCity == null ? null : destinationCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.ship_price
     *
     * @return the value of order_form.ship_price
     *
     * @mbg.generated
     */
    public Long getShipPrice() {
        return shipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.ship_price
     *
     * @param shipPrice the value for order_form.ship_price
     *
     * @mbg.generated
     */
    public void setShipPrice(Long shipPrice) {
        this.shipPrice = shipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.dispatching_price
     *
     * @return the value of order_form.dispatching_price
     *
     * @mbg.generated
     */
    public Long getDispatchingPrice() {
        return dispatchingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.dispatching_price
     *
     * @param dispatchingPrice the value for order_form.dispatching_price
     *
     * @mbg.generated
     */
    public void setDispatchingPrice(Long dispatchingPrice) {
        this.dispatchingPrice = dispatchingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.transport_price
     *
     * @return the value of order_form.transport_price
     *
     * @mbg.generated
     */
    public Long getTransportPrice() {
        return transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.transport_price
     *
     * @param transportPrice the value for order_form.transport_price
     *
     * @mbg.generated
     */
    public void setTransportPrice(Long transportPrice) {
        this.transportPrice = transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.total_price
     *
     * @return the value of order_form.total_price
     *
     * @mbg.generated
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.total_price
     *
     * @param totalPrice the value for order_form.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.vehicle
     *
     * @return the value of order_form.vehicle
     *
     * @mbg.generated
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.vehicle
     *
     * @param vehicle the value for order_form.vehicle
     *
     * @mbg.generated
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle == null ? null : vehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_form.notes
     *
     * @return the value of order_form.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_form.notes
     *
     * @param notes the value for order_form.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}