package model;

public class UserGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.ug_number
     *
     * @mbg.generated
     */
    private String ugNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.ug_name
     *
     * @mbg.generated
     */
    private String ugName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.ug_number
     *
     * @return the value of user_group.ug_number
     *
     * @mbg.generated
     */
    public String getUgNumber() {
        return ugNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.ug_number
     *
     * @param ugNumber the value for user_group.ug_number
     *
     * @mbg.generated
     */
    public void setUgNumber(String ugNumber) {
        this.ugNumber = ugNumber == null ? null : ugNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.ug_name
     *
     * @return the value of user_group.ug_name
     *
     * @mbg.generated
     */
    public String getUgName() {
        return ugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.ug_name
     *
     * @param ugName the value for user_group.ug_name
     *
     * @mbg.generated
     */
    public void setUgName(String ugName) {
        this.ugName = ugName == null ? null : ugName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.notes
     *
     * @return the value of user_group.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.notes
     *
     * @param notes the value for user_group.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}