package dao;

import java.util.List;
import model.CityRegion;

public interface CityRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_region
     *
     * @mbg.generated
     */
    int insert(CityRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_region
     *
     * @mbg.generated
     */
    CityRegion selectByPrimaryKey(String regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_region
     *
     * @mbg.generated
     */
    List<CityRegion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CityRegion record);
}