package dao;

import java.util.List;
import model.ConnectFrom;

public interface ConnectFromMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect_from
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String originCity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect_from
     *
     * @mbg.generated
     */
    int insert(ConnectFrom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect_from
     *
     * @mbg.generated
     */
    ConnectFrom selectByPrimaryKey(String originCity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect_from
     *
     * @mbg.generated
     */
    List<ConnectFrom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connect_from
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConnectFrom record);
}