package dao;

import java.util.List;
import model.Vehicle;

public interface VehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    int insert(Vehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    Vehicle selectByPrimaryKey(String vehicleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    List<Vehicle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Vehicle record);
}